---
sidebar: sidebar 
permalink: technical-reports/commvault-index.html 
keywords: Backup, on-premises, commvault, storagegrid, object, S3, WORM 
summary: 고객과 NetApp IT가 구현한 StorageGRID 구성에 대한 몇 가지 사용 사례를 살펴보십시오. 
---
= StorageGRID 및 Commvault를 사용하여 데이터를 백업하고 복구합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
CommVault와 NetApp은 파트너 관계를 통해 Commvault의 전체 백업 및 복구 NetApp 기능을 클라우드 스토리지용 NetApp StorageGRID 소프트웨어와 결합하여 공동 데이터 보호 솔루션을 구축했습니다. CommVault의 완벽한 백업 및 복구 및 NetApp StorageGRID는 전 세계적으로 빠르게 증가하는 데이터 및 늘어나는 규제에 대한 요구 사항을 충족할 수 있도록 지원하는 사용하기 쉬운 고유한 솔루션을 제공합니다.

많은 조직은 스토리지를 클라우드로 마이그레이션하고, 시스템을 확장하고, 데이터의 장기 보존을 위한 정책을 자동화하려고 합니다. 클라우드 기반 오브젝트 스토리지는 복원력, 확장 기능, 운영 및 비용 효율성으로 잘 알려져 있으며, 이를 백업 대상으로 자연스럽게 선택할 수 있습니다. CommVault와 NetApp는 2014년에 통합 솔루션을 공동으로 인증했으며 그 이후 두 솔루션 간의 통합을 더욱 강화했습니다. 전 세계 모든 유형의 고객이 Commvault Complete 백업 및 복구 및 StorageGRID 통합 솔루션을 채택했습니다.



== Commvault 및 StorageGRID 정보

CommVault Complete Backup and Recovery 소프트웨어는 처음부터 단일 플랫폼에서 통합된 코드 베이스로 구축된 엔터프라이즈급 통합 데이터 및 정보 관리 솔루션입니다. 모든 기능은 백엔드 기술을 공유하므로 데이터 보호, 관리 및 액세스에 대해 완벽하게 통합된 접근 방식의 탁월한 장점과 이점을 제공합니다. 이 소프트웨어에는 데이터를 보호, 보관, 분석, 복제 및 검색하는 모듈이 포함되어 있습니다. 이 모듈은 서로 원활하게 상호 작용하는 공통 백엔드 서비스와 고급 기능을 공유합니다. 이 솔루션은 기업의 모든 데이터 관리 측면을 해결하는 동시에 무한한 확장성과 데이터 및 정보에 대한 전례 없는 제어를 제공합니다.

Commvault 클라우드 계층인 NetApp StorageGRID는 엔터프라이즈 하이브리드 클라우드 오브젝트 스토리지 솔루션입니다. 이 제품은 특별 제작된 어플라이언스나 소프트웨어 정의 구축을 통해 여러 사이트에 배포할 수 있습니다. StorageGRID을 사용하면 데이터를 저장 및 보호하는 방법을 결정하는 데이터 관리 정책을 설정할 수 있습니다. StorageGRID는 정책을 개발하고 적용하는 데 필요한 정보를 수집합니다. 또한 성능, 내구성, 가용성, 지리적 위치, 운영 효율성 요구사항을 비롯한 다양한 특성과 요구사항을 지속 가능성, 비용. 데이터는 여러 위치 간에 이동하는 동안 또는 데이터가 노후화되는 시기에 완벽하게 관리되고 보호됩니다.

StorageGRID 지능형 정책 엔진을 활용하면 다음 옵션 중 하나를 선택할 수 있습니다.

* 삭제 코딩을 사용하여 복원력을 위해 여러 사이트에서 데이터를 백업합니다.
* 오브젝트를 원격 사이트에 복사하여 WAN 지연 시간 및 비용을 최소화합니다.


StorageGRID에서 오브젝트를 저장할 때 오브젝트는 위치나 복사본의 수에 상관없이 하나의 오브젝트로 액세스합니다. 이 동작은 재해 복구에 매우 중요합니다. 데이터의 백업 복사본 하나가 손상된 경우에도 StorageGRID에서 데이터를 복원할 수 있기 때문입니다.

백업 데이터를 기본 스토리지에 보관하는 것은 비용이 많이 들 수 있습니다. NetApp StorageGRID를 사용하면 비활성 백업 데이터를 StorageGRID로 마이그레이션하여 기본 스토리지의 공간을 늘릴 수 있고 StorageGRID의 다양한 기능을 활용할 수 있습니다. 시간이 지나면 백업 데이터의 가치가 변경되고 백업 데이터를 저장하는 비용도 변경됩니다. StorageGRID를 사용하면 운영 스토리지의 비용을 최소화하면서 데이터의 내구성을 높일 수 있습니다.



== 주요 기능

Commvault 소프트웨어 플랫폼의 주요 기능은 다음과 같습니다.

* 가상 및 물리적 서버, NAS 시스템, 클라우드 기반 인프라 및 모바일 장치에서 모든 주요 운영 체제, 애플리케이션 및 데이터베이스를 지원하는 완벽한 데이터 보호 솔루션입니다.
* 단일 콘솔을 통한 간편한 관리: 기업 전체의 모든 기능과 모든 데이터 및 정보를 보고 관리하고 액세스할 수 있습니다.
* 데이터 백업 및 아카이빙, 스냅샷 관리, 데이터 복제, e-discovery용 콘텐츠 인덱싱 등 다양한 보호 방법
* 디스크 및 클라우드 스토리지에 대한 중복 제거 기능을 사용하여 스토리지를 효율적으로 관리
* AFF, FAS, NetApp HCI, E-Series 어레이 및 NetApp SolidFire ® 스케일아웃 스토리지 시스템과 같은 NetApp 스토리지 시스템과의 통합 또한 NetApp Cloud Volumes ONTAP 소프트웨어와 통합하여 NetApp 스토리지 포트폴리오 전반에서 인덱싱된 애플리케이션 인식 NetApp Snapshot ™ 복사본 생성을 자동화합니다.
* 업계 최고의 온프레미스 가상 하이퍼바이저 및 퍼블릭 클라우드 하이퍼스케일러 플랫폼을 지원하는 완벽한 가상 인프라 관리
* 고급 보안 기능으로 중요한 데이터에 대한 액세스를 제한하고, 세분화된 관리 기능을 제공하며, Active Directory 사용자에게 SSO(Single Sign-On) 액세스를 제공합니다.
* 정책 기반 데이터 관리: 물리적 위치가 아닌 비즈니스 요구사항에 따라 데이터를 관리할 수 있도록 지원합니다.
* 사용자가 데이터를 보호, 검색 및 복구할 수 있는 최첨단 최종 사용자 환경을 제공합니다.
* API 기반 자동화를 통해 vRealize Automation 또는 Service Now와 같은 타사 툴을 사용하여 데이터 보호 및 복구 작업을 관리할 수 있습니다.


지원되는 워크로드에 대한 자세한 내용은 를 https://www.commvault.com/supported-technologies["CommVault의 지원 기술"]참조하십시오.



== 백업 옵션

Commvault Complete 백업 및 복구 소프트웨어와 클라우드 스토리지를 구축한 경우 두 가지 백업 옵션이 있습니다.

* 운영 디스크 타겟에 백업하고 클라우드 스토리지에 보조 복사본을 백업합니다.
* 1차 타겟으로 클라우드 스토리지에 백업


과거에는 클라우드 또는 오브젝트 스토리지 성능이 운영 백업에 너무 낮은 것으로 간주되었습니다. 기본 디스크 타겟을 사용하면 백업 및 복원 프로세스가 더 빨라졌으며, 클라우드에 보조 복사본을 콜드 백업으로 유지할 수 있었습니다. StorageGRID은 차세대 오브젝트 스토리지를 나타냅니다. StorageGRID는 다른 오브젝트 스토리지 공급업체보다 뛰어난 성능과 높은 처리량뿐만 아니라 성능 및 유연성을 제공할 수 있습니다.

다음 표에는 StorageGRID의 각 백업 옵션의 이점이 나와 있습니다.

[cols="1a,1a,1a"]
|===
|  | 디스크에 대한 기본 백업 및 StorageGRID에 대한 보조 복사 | StorageGRID에 기본 백업 


 a| 
성능
 a| 
라이브 마운트 또는 라이브 복구를 사용하는 가장 빠른 복구 시간: 계층 0/계층 1 워크로드에 가장 적합합니다.
 a| 
라이브 마운트 또는 라이브 복구 작업에 사용할 수 없습니다. 스트리밍 복원 작업 및 장기 보존에 적합합니다.



 a| 
구축 아키텍처
 a| 
첫 번째 백업 랜딩 계층으로 All-Flash 또는 회전식 디스크를 사용합니다. StorageGRID는 보조 계층으로 사용됩니다.
 a| 
StorageGRID를 포괄적인 백업 타겟으로 사용하여 구축을 단순화합니다.



 a| 
고급 기능(실시간 복원)
 a| 
지원
 a| 
지원되지 않습니다

|===


== 추가 정보를 찾을 수 있는 위치

이 문서에 설명된 정보에 대해 자세히 알아보려면 다음 문서 및/또는 웹 사이트를 검토하십시오.

* StorageGRID 11.9 설명서 센터+ https://docs.netapp.com/us-en/storagegrid-119/[]
* NetApp 제품 설명서 +
https://docs.netapp.com[]
* Commvault 설명서 +
https://documentation.commvault.com/2024/essential/index.html[]

