---
sidebar: sidebar 
permalink: technical-reports/data-security-platform-security.html 
keywords: platform security, storagegrid 
summary: StorageGRID의 플랫폼 보안 기능에 대해 알아봅니다. 
---
= 플랫폼 보안 기능
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
StorageGRID의 플랫폼 보안 기능에 대해 알아봅니다.

[cols="20,30a,30,20"]
|===
| 피처 | 기능 | 영향 | 규정 준수 


| 내부 PKI(공개 키 인프라), 노드 인증서 및 TLS  a| 
StorageGRID는 내부 PKI 및 노드 인증서를 사용하여 노드 간 통신을 인증하고 암호화합니다. 노드 간 통신은 TLS에 의해 보호됩니다.
| LAN 또는 WAN을 통한 시스템 트래픽 보안, 특히 다중 사이트 구축 시 유용합니다. | SEC 규정 17a-4(f) CTFC 1.31(c) -(d)(FINRA) 규칙 4511(c) 


| 노드 방화벽  a| 
StorageGRID는 IP 테이블 및 방화벽 규칙을 자동으로 구성하여 들어오는 네트워크 트래픽과 나가는 네트워크 트래픽을 제어하고 사용되지 않는 포트를 닫습니다.
| StorageGRID 시스템, 데이터 및 메타데이터를 원치 않는 네트워크 트래픽으로부터 보호합니다. | -- 


| OS 강화  a| 
StorageGRID 물리적 어플라이언스 및 가상 노드의 기본 운영 체제가 강화되며 관련 없는 소프트웨어 패키지가 제거됩니다.
| 잠재적인 공격 대상을 최소화합니다. | SEC 규정 17a-4(f) CTFC 1.31(c) -(d)(FINRA) 규칙 4511(c) 


| 주기적인 플랫폼 및 소프트웨어 업데이트  a| 
StorageGRID는 운영 체제, 응용 프로그램 바이너리 및 소프트웨어 업데이트를 포함하는 정기적인 소프트웨어 릴리즈를 제공합니다.
| StorageGRID 시스템을 최신 소프트웨어 및 응용 프로그램 바이너리로 업데이트하는 데 도움이 됩니다. | -- 


| SSH(Secure Shell)를 통한 루트 로그인 비활성화  a| 
모든 StorageGRID 노드에서 SSH를 통한 루트 로그인이 비활성화됩니다. SSH 액세스에서는 인증서 인증을 사용합니다.
| 고객이 루트 로그인의 잠재적인 원격 암호 크래킹으로부터 보호할 수 있습니다. | SEC 규정 17a-4(f) CTFC 1.31(c) -(d)(FINRA) 규칙 4511(c) 


| 자동 시간 동기화  a| 
StorageGRID는 여러 외부 시간 네트워크 시간 프로토콜(NTP) 서버에 대해 각 노드의 시스템 클록을 자동으로 동기화합니다. Stratum 3 이상의 NTP 서버가 4개 이상 필요합니다.
| 모든 노드에서 동일한 시간 참조를 보장합니다. | SEC 규정 17a-4(f) CTFC 1.31(c) -(d)(FINRA) 규칙 4511(c) 


| 클라이언트, 관리자 및 내부 그리드 트래픽을 위한 별도의 네트워크  a| 
StorageGRID 소프트웨어 노드 및 하드웨어 어플라이언스는 여러 가상 및 물리적 네트워크 인터페이스를 지원하므로 고객이 여러 네트워크에서 클라이언트, 관리 및 내부 그리드 트래픽을 분리할 수 있습니다.
| 그리드 관리자는 내부 및 외부 네트워크 트래픽을 분리하고 서로 다른 SLA를 가진 네트워크를 통해 트래픽을 전달할 수 있습니다. | -- 


| 다중 VLAN(Virtual LAN) 인터페이스  a| 
StorageGRID는 StorageGRID 클라이언트 및 그리드 네트워크에서 VLAN 인터페이스 구성을 지원합니다.
| 그리드 관리자는 보안, 유연성 및 성능을 위해 애플리케이션 트래픽을 분할하고 격리할 수 있습니다. |  


| 신뢰할 수 없는 클라이언트 네트워크  a| 
신뢰할 수 없는 클라이언트 네트워크 인터페이스는 로드 밸런서 끝점으로 명시적으로 구성된 포트에 대해서만 인바운드 연결을 허용합니다.
| 신뢰할 수 없는 네트워크에 노출된 인터페이스의 보안을 보장합니다. | -- 


| 구성 가능한 방화벽  a| 
관리, 그리드 및 클라이언트 네트워크에 대한 열린 포트 및 닫힌 포트를 관리합니다.
| 그리드 관리자가 포트에 대한 액세스를 제어하고 포트에 대한 승인된 장치 액세스를 관리할 수 있습니다. |  


| 향상된 SSH 동작  a| 
설치 전에 기본적으로 SSH를 비활성화합니다.  기본 상태에서는 SSH 액세스는 링크 로컬 관리 포트 주소에서만 활성화됩니다.  관리자 및 루트 사용자 비밀번호는 어플라이언스 컴퓨팅 컨트롤러 일련 번호로 설정됩니다.  로그인은 직렬 콘솔과 그래픽 콘솔(BMC KVM)에서만 허용됩니다.  모든 네트워크 포트에서 SSH가 비활성화되었습니다.
| 네트워크 접근 보호를 강화합니다. | SEC 규정 17a-4(f) CTFC 1.31(c) -(d)(FINRA) 규칙 4511(c) 


| 노드 암호화  a| 
새로운 KMS 호스트 서버 암호화 기능의 일부로 새로운 노드 암호화 설정이 StorageGRID 어플라이언스 설치 프로그램에 추가됩니다.
| 이 설정은 어플라이언스 설치의 하드웨어 구성 단계에서 활성화해야 합니다. | SEC 규정 17a-4(f) CTFC 1.31(c) -(d)(FINRA) 규칙 4511(c) 
|===