---
sidebar: sidebar 
permalink: technical-reports/data-security-object-metadata-security.html 
keywords: object metadata security, storagegrid 
summary: StorageGRID의 개체 및 메타데이터 보안 기능을 살펴봅니다. 
---
= 오브젝트 및 메타데이터 보안
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
StorageGRID의 개체 및 메타데이터 보안 기능을 살펴봅니다.

[cols="20,30a,30,20"]
|===
| 피처 | 기능 | 영향 | 규정 준수 


| AES(Advanced Encryption Standard) 서버측 개체 암호화  a| 
StorageGRID는 AES 128 및 AES 256 기반의 서버측 오브젝트 암호화를 제공합니다. 그리드 관리자는 암호화를 전역 기본 설정으로 활성화할 수 있습니다. 또한 StorageGRID는 S3 x-amz-server-side 암호화 헤더를 지원하여 오브젝트별로 암호화를 활성화하거나 비활성화할 수 있습니다. 이 기능을 활성화하면 저장 또는 그리드 노드 간에 전송 중인 객체가 암호화됩니다.
| 기본 스토리지 하드웨어에 관계없이 안전하게 개체를 저장하고 전송할 수 있습니다. | SEC 규정 17a-4(f) CTFC 1.31(c) -(d)(FINRA) 규칙 4511(c) 


| 내장된 키 관리  a| 
암호화가 활성화되면 각 오브젝트가 무작위로 생성된 고유 대칭 키로 암호화되며 외부 액세스 없이 StorageGRID 내에 저장됩니다.
| 외부 키 관리 없이도 개체 암호화 가능 |  


| FIPS(Federal Information Processing Standard) 140-2 준수 암호화 디스크  a| 
SG5812, SG5860, SG6160 및 SGF6024 StorageGRID 어플라이언스는 FIPS 140-2 준수 암호화 디스크의 옵션을 제공합니다. 선택적으로 외부 KMIP 서버를 통해 디스크의 암호화 키를 관리할 수 있습니다.
| 시스템 데이터, 메타데이터 및 오브젝트의 안전한 스토리지 지원 또한 StorageGRID 소프트웨어 기반 오브젝트 암호화를 제공하여 오브젝트의 저장 및 전송을 보호합니다. | SEC 규정 17a-4(f) CTFC 1.31(c) -(d)(FINRA) 규칙 4511(c) 


| 노드에 대한 연방 정보 처리 표준(FIPS) 140-3 호환 암호화  a| 
SG5812, SG5860, SG6160, SGF6112, SG1100 및 SG110 StorageGRID 어플라이언스는 FIPS 140-3 호환 노드 암호화 옵션을 제공합니다.  노드의 암호화 키는 외부 KMIP 서버에서 관리합니다.
| 시스템 데이터, 메타데이터 및 오브젝트의 안전한 스토리지 지원 또한 StorageGRID 소프트웨어 기반 오브젝트 암호화를 제공하여 오브젝트의 저장 및 전송을 보호합니다. | SEC 규정 17a-4(f) CTFC 1.31(c) -(d)(FINRA) 규칙 4511(c) 


| 백그라운드 무결성 검사 및 자가 복구  a| 
StorageGRID는 오브젝트 및 하위 오브젝트 수준에서 해시, 체크섬, 순환 중복 검사(CRC)의 인터잠금 메커니즘을 사용하여 오브젝트가 스토리지에 있을 때와 전송 중일 때 데이터 비일관성, 변조 또는 수정으로부터 보호합니다. StorageGRID는 손상되거나 무단 변경된 오브젝트를 자동으로 감지하여 교체하는 한편, 변경된 데이터를 격리하고 관리자에게 경고합니다.
| 그리드 관리자는 데이터 내구성과 관련된 SLA, 규정 및 기타 의무를 충족할 수 있습니다. 고객이 데이터를 암호화, 변조 또는 수정하려는 랜섬웨어 또는 바이러스를 감지하는 데 도움이 됩니다. | SEC 규정 17a-4(f) CTFC 1.31(c) -(d)(FINRA) 규칙 4511(c) 


| 정책 기반 오브젝트 배치 및 보존  a| 
StorageGRID를 통해 그리드 관리자는 객체 보존, 배치, 보호, 전환 및 만료가 지정된 ILM 규칙을 구성할 수 있습니다. 그리드 관리자는 StorageGRID 메타데이터로 오브젝트를 필터링하고 그리드 전체, 테넌트, 버킷, 키 접두사, 및 사용자 정의 메타데이터 키-값 쌍 StorageGRID는 클라이언트에서 명시적으로 삭제하지 않는 한, 라이프사이클 전반에서 ILM 규칙에 따라 오브젝트를 저장할 수 있도록 도와줍니다.
| 데이터 배치, 보호 및 보존을 적용할 수 있도록 지원 고객이 내구성, 가용성, 성능에 대한 SLA를 달성할 수 있도록 지원합니다. | SEC 규정 17a-4(f) CTFC 1.31(c) -(d)(FINRA) 규칙 4511(c) 


| 백그라운드 메타데이터 검사  a| 
StorageGRID은 주기적으로 백그라운드에서 오브젝트 메타데이터를 검사하여 ILM에서 지정한 대로 오브젝트 데이터 배치 또는 보호 변경 사항을 적용합니다.
| 손상된 개체를 찾는 데 도움이 됩니다. |  


| 일관성 조정 가능  a| 
테넌트는 버킷 수준의 일관성 수준을 선택하여 다중 사이트 연결과 같은 리소스를 사용할 수 있도록 할 수 있습니다.
| 필요한 수의 사이트 또는 리소스를 사용할 수 있는 경우에만 그리드에 쓰기를 커밋하는 옵션을 제공합니다. |  
|===