---
sidebar: sidebar 
permalink: technical-reports/load-balancer-storagegrid.html 
keywords: object storage, load balancer 
summary: StorageGRID 로드 밸런서의 역할에 대해 알아보세요. 
---
= StorageGRID 로드 밸런서 사용
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
StorageGRID Gateway Node 로드 밸런서의 역할에 대해 알아보세요.

NetApp® StorageGRID® 게이트웨이 노드를 구현하기 위한 일반 지침입니다.



== StorageGRID 게이트웨이 노드 로드 밸런서 대 타사 로드 밸런서

StorageGRID는 S3 호환 오브젝트 스토리지 공급업체에서는 특별 제작된 어플라이언스, VM 또는 컨테이너로 제공되는 네이티브 로드 밸런서를 제공한다는 점에서 차별화됩니다. StorageGRID에서 제공하는 로드 밸런서를 게이트웨이 노드라고도 합니다.

F5, Citrix 등과 같은 로드 밸런서를 아직 소유하고 있지 않은 고객의 경우 타사 로드 밸런서를 구현하는 것이 매우 복잡할 수 있습니다. StorageGRID 로드 밸런서는 로드 밸런서 운영을 크게 단순화합니다.

게이트웨이 노드는 고가용성 및 고성능 로드 밸런서입니다. 고객은 게이트웨이 노드, 타사 로드 밸런서 또는 둘 다를 동일한 그리드에 구현할 수 있습니다. 게이트웨이 노드는 GSLB와 로컬 트래픽 관리자입니다.

StorageGRID 로드 밸런서는 다음과 같은 이점을 제공합니다.

* * 단순성 *. 리소스 풀 자동 구성, 상태 점검, 패치 적용 및 유지 관리 기능이 모두 StorageGRID에서 관리됩니다.
* *성능*.  StorageGRID 로드 밸런서는 StorageGRID 전용으로, 고성능 캐싱을 제공하며, 대역폭을 놓고 다른 애플리케이션과 경쟁하지 않습니다.
* * 비용 *. 추가 비용 없이 가상 머신(VM) 및 컨테이너 버전이 제공됩니다.
* * 트래픽 분류 *. 고급 트래픽 분류 기능을 사용하면 워크로드 분석과 함께 StorageGRID 관련 QoS 규칙을 사용할 수 있습니다.
* * 미래의 StorageGRID 전용 기능 *. StorageGRID는 향후 릴리스에 걸쳐 로드 밸런서에 혁신적인 기능을 지속적으로 최적화하고 추가할 예정입니다.


StorageGRID 의 통합 노드로서 로컬 트래픽 관리자는 고급 상태 검사를 사용하여 스토리지 노드 상태, 부하 및 리소스 가용성에 따라 요청을 분산할 수 있습니다.  또한 StorageGRID 링크 비용이 사이트 간에 "0"으로 설정된 경우 여러 사이트에 부하를 분산하는 기능도 있습니다.  스토리지 노드를 사용할 수 없지만 게이트웨이 노드를 사이트에서 사용할 수 있는 경우, 부하가 자동으로 그리드의 다른 사이트로 전달됩니다.

게이트웨이 노드의 로드 밸런서 캐싱 기능은 데이터 처리의 일환으로 데이터 세트를 여러 번 다시 읽는 특정 작업 부하(예: AI 학습)에 대해 상당한 성능 향상을 제공하기 위한 것입니다.  캐싱 게이트웨이 노드는 그리드의 나머지 부분과 물리적으로 떨어진 곳에 배치하여 일부 작업 부하에서 더 나은 성능을 제공하고 WAN 네트워크 활용도를 낮출 수도 있습니다.  캐시는 쓰기가 캐시되지 않고 캐시 상태를 수정하지 않는 읽기 모드에서 작동합니다.  각 캐싱 게이트웨이 노드는 다른 캐싱 게이트웨이 노드와 독립적으로 작동합니다.

StorageGRID Gateway 노드 배포에 대한 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/storagegrid/["StorageGRID 설명서"^] .
