---
sidebar: sidebar 
permalink: technical-reports/load-balancer-local-traffic-manager-load-balancer.html 
keywords: local traffic manager, load balancer 
summary: 로컬 트래픽 관리자 로드 밸런서에 대한 지침을 살펴보고 최적의 구성을 결정합니다. 
---
= 로컬 트래픽 매니저 로드 밸런서에 대해 알아보십시오
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
로컬 트래픽 관리자 로드 밸런서에 대한 지침을 살펴보고 최적의 구성을 결정합니다.

다음은 타사 로드 밸런서 구성에 대한 일반적인 지침입니다. 로드 밸런서 관리자와 협력하여 사용자 환경에 가장 적합한 구성을 결정합니다.



== 스토리지 노드의 리소스 그룹을 생성합니다

StorageGRID 스토리지 노드를 리소스 풀 또는 서비스 그룹으로 그룹화합니다(용어는 특정 로드 밸런서에 따라 다를 수 있음). StorageGRID 스토리지 노드는 다음 포트에 S3 API를 제공합니다.

* S3 HTTPS: 18082
* S3 HTTP: 18084


대부분의 고객은 표준 HTTPS 및 HTTP 포트(443 및 80)를 통해 가상 서버에서 API를 제공하도록 선택합니다.


NOTE: 각 StorageGRID 사이트에는 3개의 스토리지 노드가 기본적으로 필요하고 2개는 정상 상태여야 합니다.



== 상태 점검

타사 로드 밸런서를 사용하려면 각 노드의 상태와 해당 노드의 트래픽 수신 자격을 확인하는 방법이 필요합니다. NetApp에서는 상태 점검을 수행할 것을 HTTP `OPTIONS` 메소드를 권장합니다. 로드 밸런서는 각 개별 스토리지 노드에 HTTP `OPTIONS` 요청을 전송하고 상태 응답을 예상합니다. `200`

스토리지 노드가 응답을 제공하지 않으면 `200` 해당 노드에서 스토리지 요청을 처리할 수 없습니다. 애플리케이션 및 비즈니스 요구 사항에 따라 이러한 확인 시간 초과 및 로드 밸런서가 수행하는 작업이 결정됩니다.

예를 들어, 데이터 센터 1에 있는 4개의 스토리지 노드 중 3개가 중단된 경우 모든 트래픽을 데이터 센터 2로 전달할 수 있습니다.

권장되는 폴링 간격은 초당 1회이며, 세 번의 검사가 실패한 후 노드가 오프라인 상태로 표시됩니다.



=== S3 상태 점검의 예

다음 예에서는 `OPTIONS` 를 보내고 `200 OK`확인합니다.  `OPTIONS`Amazon S3)가 승인되지 않은 요청을 지원하지 않기 때문에 사용합니다.

[listing, subs="verbatim,quotes"]
----
##curl -X OPTIONS https://10.63.174.75:18082 --verbose --insecure##
* Rebuilt URL to: https://10.63.174.75:18082/
*   Trying 10.63.174.75...
* TCP_NODELAY set
* Connected to 10.63.174.75 (10.63.174.75) port 18082 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate: webscale.stl.netapp.com
* Server certificate: NetApp Corp Issuing CA 1
* Server certificate: NetApp Corp Root CA
> OPTIONS / HTTP/1.1
> Host: 10.63.174.75:18082
> User-Agent: curl/7.51.0
> Accept: */*
>
< HTTP/1.1 ##200 OK##
< Date: Mon, 22 May 2017 15:17:30 GMT
< Connection: KEEP-ALIVE
< Server: StorageGRID/10.4.0
< x-amz-request-id: 3023514741
----


=== 파일 또는 콘텐츠 기반의 상태 점검

일반적으로 NetApp은 파일 기반 상태 점검을 권장하지 않습니다. 예를 들어, 일반적으로 작은 파일이 —`healthcheck.htm`읽기 전용 정책으로 버킷에서 생성됩니다. 그런 다음 로드 밸런서에 의해 이 파일을 가져와 평가합니다. 이 접근 방식에는 몇 가지 단점이 있습니다.

* *단일 계정에 따라 다릅니다.* 파일을 소유한 계정이 비활성화되면 상태 점검이 실패하고 스토리지 요청이 처리되지 않습니다.
* * 데이터 보호 규칙. * 기본 데이터 보호 체계는 두 가지 복사본 접근 방식입니다. 이 시나리오에서는 상태 점검 파일을 호스팅하는 두 스토리지 노드를 사용할 수 없는 경우 상태 점검이 실패하고 스토리지 요청이 정상적인 스토리지 노드로 전송되지 않아 그리드가 오프라인으로 렌더링됩니다.
* * 감사 로그 블로트. * 로드 밸런서는 매 X 분마다 모든 스토리지 노드에서 파일을 가져와 감사 로그 항목을 많이 생성합니다.
* * 리소스 집약적 * 몇 초마다 모든 노드에서 상태 점검 파일을 가져오면 그리드 및 네트워크 리소스가 사용됩니다.


콘텐츠 기반의 상태 점검이 필요한 경우 전용 S3 버킷이 있는 전용 테넌트를 사용하십시오.



=== 세션 지속성

세션 지속성 또는 고정성은 지정된 HTTP 세션이 지속될 수 있는 시간을 나타냅니다. 기본적으로 세션은 10분 후에 스토리지 노드에 의해 삭제됩니다. 지속성 시간이 길어지면 애플리케이션이 모든 작업에 대해 세션을 다시 설정할 필요가 없으므로 성능이 향상될 수 있지만 이러한 세션을 열어 두면 리소스가 소모됩니다. 작업 부하가 유용하다고 판단되면 타사 로드 밸런서의 세션 지속성을 줄일 수 있습니다.



== 가상 호스팅 방식의 주소 지정

이제 가상 호스팅 방식이 AWS S3의 기본 방법이며 StorageGRID와 많은 애플리케이션이 경로 스타일을 지원하는 반면, 호스팅된 가상 지원을 구축하는 것이 모범 사례입니다. 가상 호스팅 방식의 요청에는 호스트 이름의 일부분으로 버켓이 있습니다.

가상 호스팅 스타일을 지원하려면 다음을 수행합니다.

* 와일드카드 DNS 조회 지원: * .s3.company.com
* 와일드카드를 지원하려면 제목 대체 이름이 있는 SSL 인증서를 사용하십시오. *.s3.company.com 일부 고객은 와일드카드 인증서 사용과 관련하여 보안 문제를 제기했습니다. StorageGRID는 FabricPool와 같은 주요 애플리케이션과 마찬가지로 경로 스타일 액세스를 계속 지원합니다. 하지만 가상 호스팅 지원 없이는 특정 S3 API 호출이 실패하거나 제대로 작동하지 않습니다.




== SSL 종료

타사 로드 밸런서의 SSL 종료에는 보안상의 이점이 있습니다. 로드 밸런서가 손상되면 그리드가 분리됩니다.

지원되는 구성은 세 가지입니다.

* * SSL 패스스루. * SSL 인증서는 StorageGRID에 사용자 지정 서버 인증서로 설치됩니다.
* * SSL 종료 및 재암호화(권장). * StorageGRID에 SSL 인증서를 설치하지 않고 로드 밸런서에서 SSL 인증서 관리를 이미 수행하고 있는 경우 이 방법이 도움이 될 수 있습니다. 이 구성은 공격 대상을 로드 밸런서까지 제한하는 추가적인 보안 이점을 제공합니다.
* * HTTP로 SSL 종료. * 이 구성에서 SSL은 타사 로드 밸런서에서 종료되며 로드 밸런서에서 StorageGRID로의 통신은 SSL 오프로드를 활용하기 위해 암호화되지 않습니다(최신 프로세서에 내장된 SSL 라이브러리 사용).




== 패스스루 구성

패스스루에 대해 로드 밸런서를 구성하려면 StorageGRID에 인증서를 설치해야 합니다. 메뉴: 구성 [서버 인증서 > 개체 스토리지 API 서비스 끝점 서버 인증서]로 이동합니다.



== 소스 클라이언트 IP 가시성

StorageGRID 11.4에는 신뢰할 수 있는 타사 로드 밸런서라는 개념이 도입되었습니다. 클라이언트 응용 프로그램 IP를 StorageGRID로 전달하려면 이 기능을 구성해야 합니다. 자세한 내용은 을 참조하십시오 https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_configure_StorageGRID_to_work_with_third-party_Layer_7_load_balancers["타사 레이어 7 로드 밸런서와 함께 작동하도록 StorageGRID를 구성하는 방법"^]

클라이언트 응용 프로그램의 IP를 보는 데 XFF 헤더를 사용하도록 설정하려면 다음 단계를 수행하십시오.

.단계
. 감사 로그에 클라이언트 IP를 기록합니다.
.  `aws:SourceIp`S3 버킷 또는 그룹 정책을 사용합니다.




=== 로드 밸런싱 전략

대부분의 로드 밸런싱 솔루션은 로드 밸런싱을 위한 여러 전략을 제공합니다. 다음은 일반적인 전략입니다.

* * 라운드 로빈. * 보편적인 적합하지만 소수의 노드와 대규모 전송으로 인해 단일 노드가 어려움을 겪고 있습니다.
* * 최소 연결. * 소형 및 혼합 오브젝트 워크로드에 적합하며, 모든 노드에 대한 연결의 균등한 분산을 제공합니다.


알고리즘 선택은 선택할 스토리지 노드의 수가 늘어날수록 더 중요해집니다.



=== 데이터 경로

모든 데이터는 로컬 트래픽 관리자 로드 밸런서를 통해 흐릅니다. StorageGRID는 DSR(Direct Server Routing)을 지원하지 않습니다.



==== 연결 배포를 확인하는 중입니다

메서드가 스토리지 노드 전체에 로드를 균등하게 분산하는지 확인하려면 지정된 사이트의 각 노드에서 설정된 세션을 확인합니다.

* * UI 방법. * 메뉴로 이동: 지원 [메트릭 > S3 개요 > LDR HTTP 세션]
* * 메트릭 API. * 사용 `storagegrid_http_sessions_incoming_currently_established`

