---
permalink: technical-reports/monitor-index.html 
sidebar: sidebar 
keywords: monitoring, storagegrid 
summary: NetApp StorageGRID, 오류 상태 및 Splunk와 같은 외부 애플리케이션을 사용하여 효과적으로 모니터링하는 방법에 대해 자세히 살펴봅니다. 
---
= StorageGRID 모니터링 소개
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Splunk와 같은 외부 애플리케이션을 사용하여 StorageGRID 시스템을 모니터링하는 방법에 대해 알아보십시오.

NetApp StorageGRID 오브젝트 기반 스토리지를 효과적으로 모니터링하여 관리자는 긴급한 문제에 빠르게 대응하고 인력을 사전에 추가하여 증가하는 워크로드를 처리할 수 있습니다. 이 보고서에서는 주요 지표를 모니터링하는 방법과 외부 모니터링 애플리케이션을 활용하는 방법에 대한 일반적인 지침을 제공합니다. 기존의 모니터링 및 문제 해결 가이드를 보완하기 위한 것입니다.

NetApp StorageGRID 구축은 일반적으로 여러 사이트와 다수의 노드로 구성되며 내결함성이 있는 분산 오브젝트 스토리지 시스템을 구축하는 데 필요한 다수의 노드로 구성됩니다. StorageGRID와 같은 분산 및 복구 기능이 있는 스토리지 시스템에서는 그리드가 계속 정상적으로 작동하는 동안 오류 상태가 발생하는 것이 정상입니다. 관리자의 과제는 오류 조건(예: 노드 다운)이 문제를 즉시 해결해야 하는 임계값과 분석해야 하는 정보를 파악하는 것입니다. StorageGRID에서 제공하는 데이터를 분석하면 워크로드를 이해하고 리소스를 더 추가해야 하는 경우와 같은 정보에 입각한 의사 결정을 내릴 수 있습니다.

StorageGRID는 모니터링의 주제를 자세히 살펴보는 훌륭한 문서를 제공합니다. 이 보고서에서는 사용자가 StorageGRID에 대해 잘 알고 있고 해당 문서에 대한 문서를 검토한 것으로 가정합니다. NetApp은 이 정보를 반복하는 대신 이 가이드 전체에서 제품 설명서를 참조합니다. StorageGRID 제품 설명서는 온라인에서 PDF 형식으로 제공됩니다.

이 문서의 목표는 제품 설명서를 보완하고 Splunk와 같은 외부 애플리케이션을 사용하여 StorageGRID 시스템을 모니터링하는 방법에 대해 논의하는 것입니다.



== 데이터 소스

NetApp StorageGRID를 성공적으로 모니터링하려면 StorageGRID 시스템의 상태 및 운영에 대한 데이터를 수집할 위치를 파악하는 것이 중요합니다.

* * 웹 UI 및 대시보드. * StorageGRID 그리드 관리자는 관리자가 논리적 프레젠테이션에서 확인해야 하는 정보의 최상위 보기를 제공합니다. 관리자는 문제 해결 및 로그 수집을 위한 서비스 수준 정보를 더욱 자세히 살펴볼 수도 있습니다.
* * 감사 로그. * StorageGRID는 PUT, GET, 삭제와 같은 테넌트 작업의 세부적인 감사 로그를 유지합니다. 또한 수집부터 데이터 관리 규칙의 애플리케이션에 이르기까지 오브젝트의 라이프사이클을 추적할 수 있습니다.
* * 메트릭 API. * StorageGRID GMI의 기반이 되는 API는 API 기반이므로 개방형 API입니다. 이 접근 방식을 사용하면 외부 모니터링 및 분석 툴을 사용하여 데이터를 추출할 수 있습니다.




== 추가 정보를 찾을 수 있는 위치

이 문서에 설명된 정보에 대해 자세히 알아보려면 다음 문서 및/또는 웹 사이트를 검토하십시오.

* NetApp StorageGRID 문서 센터 https://docs.netapp.com/us-en/storagegrid-118/[]
* NetApp StorageGRID 지원 https://docs.netapp.com/us-en/storagegrid-enable/[]
* NetApp 제품 설명서 https://www.netapp.com/support-and-training/documentation/[]
* Splunk를 위한 NetApp StorageGRID 앱 https://splunkbase.splunk.com/app/3898/#/details[]

