---
sidebar: sidebar 
permalink: technical-reports/bare-metal/index.html 
keywords: install, storagegrid, deploy, bare metal 
summary: 베어 메탈 그리드에 StorageGRID를 설치하는 방법을 알아보십시오. 
---
= StorageGRID 설치 소개
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../../media/


[role="lead"]
베어 메탈 호스트에 StorageGRID를 설치하는 방법을 알아보십시오.

TR-4882는 NetApp StorageGRID 작업 설치를 생성하는 실용적인 단계별 지침을 제공합니다. 설치 작업은 베어 메탈 또는 Red Hat Enterprise Linux(RHEL)에서 실행되는 가상 머신(VM)에 있을 수 있습니다. 제안된 레이아웃 및 스토리지 구성에서 3개의 물리적(또는 가상) 시스템에 6개의 StorageGRID 컨테이너식 서비스를 "제한적" 설치합니다. 일부 고객은 이 TR에 나온 구현 예제를 따르면 구현 프로세스를 더 쉽게 이해할 수 있습니다.

StorageGRID 및 설치 프로세스에 대한 자세한 내용은 제품 설명서의 [설치, 업그레이드 및 핫픽스 StorageGRID]를 참조하십시오 https://docs.netapp.com/us-en/storagegrid-118/landing-install-upgrade/index.html[] .

구축을 시작하기 전에 NetApp StorageGRID 소프트웨어의 컴퓨팅, 스토리지 및 네트워킹 요구사항을 살펴보겠습니다. StorageGRID는 Podman 또는 Docker 내에서 컨테이너식 서비스로 실행됩니다. 이 모델에서 일부 요구사항은 호스트 운영 체제(StorageGRID 소프트웨어를 실행하는 Docker를 호스팅하는 OS)를 의미합니다. 또한 일부 리소스는 각 호스트 내에서 실행되는 Docker 컨테이너에 직접 할당됩니다. 이 배포에서는 하드웨어 사용을 극대화하기 위해 물리적 호스트당 두 개의 서비스를 구축하고 있습니다. 자세한 내용은 다음 섹션을 계속 link:prerequisites-install-storagegrid.html["StorageGRID를 설치하기 위한 사전 요구 사항"]진행하십시오.

이 TR에 요약된 단계를 수행하면 6개의 베어 메탈 호스트에 StorageGRID가 설치됩니다. 이제 대부분의 테스트 시나리오에서 유용한 작업 그리드 및 클라이언트 네트워크를 사용할 수 있습니다.



== 추가 정보를 찾을 수 있는 위치

본 TR에서 설명한 정보에 대해 자세히 알아보려면 다음 문서 리소스를 검토하십시오.

* NetApp StorageGRID 문서 센터 https://docs.netapp.com/us-en/storagegrid-118/[]
* NetApp StorageGRID 지원 https://docs.netapp.com/us-en/storagegrid-enable/[]
* NetApp 제품 설명서 https://www.netapp.com/support-and-training/documentation/[]

