---
sidebar: sidebar 
permalink: technical-reports/commvault/sizing.html 
keywords: Backup, on-premises, commvault, storagegrid, object, S3, WORM 
summary: 고객과 NetApp IT가 구현한 StorageGRID 구성에 대한 몇 가지 사용 사례를 살펴보십시오. 
---
= StorageGRID 사이징 가이드
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../../media/


[role="lead"]
귀사 환경의 특정 사이징에 대해서는 NetApp 데이터 보호 전문가에게 문의하십시오. NetApp 데이터 보호 전문가는 Commvault Total Backup Storage Calculator 툴을 사용하여 백업 인프라스트럭처 요구 사항을 추정할 수 있습니다. 이 도구를 사용하려면 Commvault Partner Portal에 액세스해야 합니다. 필요한 경우 액세스를 위해 등록합니다.



== Commvault 크기 조정 입력

다음 작업을 사용하여 데이터 보호 솔루션의 크기 조정을 위한 검색을 수행할 수 있습니다.

* 보호해야 하는 시스템 또는 애플리케이션/데이터베이스 워크로드와 프런트 엔드 용량(테라바이트[TB])을 식별합니다.
* 보호해야 하는 VM/파일 워크로드 및 이와 유사한 프런트엔드 용량(TB)을 식별합니다.
* 단기 및 장기 보존 요구 사항 파악
* 식별된 데이터 세트/작업 부하에 대한 일별 변경률 확인
* 향후 12개월, 24개월 및 36개월간 예상되는 데이터 증가율을 식별합니다.
* 비즈니스 요구사항에 따라 데이터 보호/복구를 위한 RTO 및 RPO 정의


이 정보를 사용할 수 있게 되면 백업 인프라스트럭처 사이징을 수행하여 필요한 스토리지 용량을 분석할 수 있습니다.



== StorageGRID 사이징 가이드

NetApp StorageGRID 사이징을 수행하기 전에 워크로드의 다음 측면을 고려하십시오.

* 사용 가능한 용량
* WORM 모드
* 평균 개체 크기입니다
* 성능 요구사항
* ILM 정책이 적용되었습니다


사용 가능한 용량은 StorageGRID로 계층화한 백업 워크로드의 크기 및 보존 일정에 맞게 조정되어야 합니다.

WORM 모드가 활성화되거나 비활성화됩니까? Commvault에서 WORM을 활성화하면 StorageGRID에서 오브젝트 잠금이 구성됩니다. 이렇게 하면 필요한 오브젝트 스토리지 용량이 증가합니다. 필요한 용량은 보존 기간 및 각 백업에서 변경된 객체 수에 따라 달라집니다.

평균 개체 크기는 StorageGRID 환경의 성능을 사이징하는 데 도움이 되는 입력 매개 변수입니다. Commvault 워크로드에 사용되는 평균 개체 크기는 백업 유형에 따라 다릅니다.

다음 표에는 백업 유형별로 평균 개체 크기가 나열되어 있으며 복원 프로세스에서 개체 저장소에서 읽는 내용이 설명되어 있습니다.

[cols="1a,1a,1a"]
|===
| 백업 유형 | 평균 개체 크기 | 복원 동작 


 a| 
StorageGRID에서 보조 복사본을 만듭니다
 a| 
32MB
 a| 
32MB 객체의 전체 읽기



 a| 
백업을 StorageGRID로 전송(중복 제거 사용)
 a| 
8MB
 a| 
1MB 랜덤 범위 읽기



 a| 
백업을 StorageGRID로 전송(중복 제거 사용 안 함)
 a| 
32MB
 a| 
32MB 객체의 전체 읽기

|===
또한 전체 백업 및 증분 백업에 대한 성능 요구 사항을 이해하면 StorageGRID 스토리지 노드의 크기를 결정하는 데 도움이 됩니다. StorageGRID ILM(정보 라이프사이클 관리) 정책 데이터 보호 방법은 Commvault 백업을 저장하는 데 필요한 용량을 결정하고 그리드 사이징에 영향을 줍니다.

StorageGRID ILM 복제는 StorageGRID에서 오브젝트 데이터를 저장하는 데 사용하는 두 가지 메커니즘 중 하나입니다. StorageGRID에서 데이터를 복제하는 ILM 규칙에 개체를 할당하면 시스템은 오브젝트 데이터의 정확한 복사본을 생성하고 이 복사본을 스토리지 노드에 저장합니다.

삭제 코딩은 StorageGRID에서 오브젝트 데이터를 저장하는 데 사용하는 두 번째 방법입니다. StorageGRID에서 삭제 코딩 복사본을 생성하도록 구성된 ILM 규칙에 오브젝트를 할당하면 오브젝트 데이터를 데이터 조각으로 분할합니다. 그런 다음 추가 패리티 조각을 계산하고 각 조각을 서로 다른 스토리지 노드에 저장합니다. 개체에 액세스하면 저장된 조각을 사용하여 다시 조립됩니다. 패리티 조각이 손상되거나 손실된 경우 삭제 코딩 알고리즘을 통해 남은 데이터 및 패리티 조각의 일부를 사용하여 해당 조각을 다시 생성할 수 있습니다.

이 두 메커니즘에는 다음과 같은 예가 보여 주는 것처럼 서로 다른 양의 스토리지가 필요합니다.

* 복제된 복사본 2개를 저장하면 스토리지 오버헤드가 두 배로 증가합니다.
* 2+1 삭제 코딩 복사본을 저장할 경우 스토리지 오버헤드가 1.5배 증가합니다.


테스트 대상인 솔루션의 경우, 단일 사이트에 엔트리 레벨의 StorageGRID 배포를 사용했습니다.

* 관리 노드: VMware 가상 머신(VM)
* 로드 밸런서: VMware VM
* 스토리지 노드: 4TB 드라이브 장착 시 SG5712 4개
* 기본 관리자 노드 및 게이트웨이 노드: 운영 워크로드 요구 사항이 최소인 VMware VM


[NOTE]
====
StorageGRID는 또한 타사 로드 밸런서를 지원합니다.

====
StorageGRID는 일반적으로 데이터를 복제하는 데이터 보호 정책을 사용하여 노드 및 사이트 수준 장애로부터 데이터를 보호하는 두 개 이상의 사이트에 구축됩니다. 데이터를 StorageGRID에 백업하면 알고리즘을 통해 안정적으로 데이터를 분리 및 재조립하는 삭제 코딩이나 여러 복사본을 사용해 데이터를 보호할 수 있습니다.

사이징 툴을 사용할 수 있으며 https://fusion.netapp.com["Fusion"] 그리드의 크기를 조정합니다.



== 확장

스토리지 노드에 스토리지를 추가하거나, 기존 사이트에 새 그리드 노드를 추가하거나, 새 데이터 센터 사이트를 추가하여 NetApp StorageGRID 시스템을 확장할 수 있습니다. 현재 시스템의 운영을 중단하지 않고도 확장을 수행할 수 있습니다.
StorageGRID는 스토리지 노드에 고성능 노드를 사용하거나 로드 밸런서와 관리 노드를 실행하는 물리적 어플라이언스에 사용하거나 노드를 추가하기만 하면 성능을 확장할 수 있습니다.

[NOTE]
====
StorageGRID 시스템 확장에 대한 자세한 내용은 를 https://docs.netapp.com/us-en/storagegrid-119/landing-expand/index.html["StorageGRID 11.9 확장 가이드"]참조하십시오.

====